# Generated by Django 5.0.3 on 2025-05-19 21:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_element', models.CharField(choices=[('FIXE', 'Elément fixe'), ('VARIABLE', 'Elément variable')], default='FIXE', max_length=10)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='Jean', max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_minimum', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('taux_fonds_soutien_patriotique', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('taux_retenue_vacation', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('point_indiciaire', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('cnss_part_patronale', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('cnss_part_employe', models.DecimalField(decimal_places=2, default=5.5, max_digits=5)),
                ('carfo_part_patronale', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('carfo_part_employe', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField(default=2025)),
                ('cloture', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DetailEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_agent', models.CharField(blank=True, max_length=50, null=True)),
                ('regime_prevoyance_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_immatriculation', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_charges_iuts', models.PositiveIntegerField(default=0)),
                ('cadre', models.IntegerField(blank=True, choices=[(1, 'Cadre supérieur'), (2, 'Cadre inférieur')], null=True)),
                ('indice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='salaire.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('payé', 'Payé'), ('non_payé', 'Non payé')], max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.periodepaiement')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.poste'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to='salaire.employe')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salaire.projet'),
        ),
        migrations.AddField(
            model_name='employe',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.projet'),
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.periodepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='SalaireElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.elementsalaire')),
                ('salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaire_elements', to='salaire.salaire')),
            ],
        ),
        migrations.AddField(
            model_name='salaire',
            name='elements',
            field=models.ManyToManyField(related_name='salaires', through='salaire.SalaireElement', to='salaire.elementsalaire'),
        ),
    ]
