# Generated by Django 5.0.3 on 2025-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='parametre',
            name='nom_entreprise',
            field=models.CharField(default="Nom de L'Entreprise", max_length=255),
        ),
    ]
