# Generated by Django 5.0.3 on 2025-05-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0002_parametre_logo_parametre_nom_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abreviation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComposantSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Libellé du composant, ex : 'Solde indiciaire'", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('BASE', 'Salaire de base'), ('PRIME', 'Prime / Sursalaire / Ancienneté'), ('HS', 'Heures supplémentaires'), ('ALLOWANCE', 'Indemnité / Allocation'), ('DEDUCTION', 'Retenue / Cotisation'), ('AUTRE', 'Autre')], default='BASE', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur par défaut', max_digits=12)),
                ('formula', models.TextField(blank=True, help_text='Formule Excel (ou équivalent) décrivant le calcul', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salaireelement',
            name='element',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='salaireelement',
            name='salaire',
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['periode', 'employe']},
        ),
        migrations.AddField(
            model_name='detailemploye',
            name='intitule_compte',
            field=models.CharField(blank=True, help_text='Intitulé du compte', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailemploye',
            name='numero_compte',
            field=models.CharField(blank=True, help_text='Numéro de compte bancaire', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_identite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='financement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('non_payé', 'Non payé'), ('en_attente', 'En attente'), ('partiellement_payé', 'Partiellement payé'), ('payé', 'Payé')], default='non_payé', max_length=20),
        ),
        migrations.AddField(
            model_name='detailemploye',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salaire.banque'),
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_de_paiement', models.CharField(choices=[('BILLETAGE', 'Paiement par chèque'), ('VIREMENT', 'Virement Bancaire')], max_length=50)),
                ('salaire_de_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_vacation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_logement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_astreinte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_technicite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_cnss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotisation_carfo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agence_caisse', models.CharField(blank=True, help_text='Agence de caisse (pour paiement par chèque)', max_length=255, null=True)),
                ('numero_compte_caisse', models.CharField(blank=True, help_text='Numéro de compte de caisse', max_length=255, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('date_cheque', models.DateField(blank=True, null=True)),
                ('informations_sup', models.JSONField(blank=True, help_text='Détails complémentaires (exonérations, primes supplémentaires, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.employe')),
                ('session_de_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.periodepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='DetailFicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_calculee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('composant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salaire.composantsalaire')),
                ('fiche_de_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(choices=[('ASSURANCE', 'Assurance Vie'), ('CAISSE_SOCIALE', 'Caisse Sociale')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche_de_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaire.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='salaire.periodepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='SignaturePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Fonction ou titre (ex: Chef de Service)', max_length=100)),
                ('nom_complet', models.CharField(max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'apparition")),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='salaire.periodepaiement')),
            ],
        ),
        migrations.DeleteModel(
            name='ElementSalaire',
        ),
        migrations.DeleteModel(
            name='Salaire',
        ),
        migrations.DeleteModel(
            name='SalaireElement',
        ),
    ]
