# Generated by Django 5.0.3 on 2025-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0003_banque_composantsalaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composantsalaire',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='indemnite_astreinte',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='indemnite_logement',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='indemnite_technicite',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='montant_vacation',
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plafond maximum pour la valeur du composant.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage appliqué dans le calcul de ce composant (ex. 10 pour 10%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seuil de référence pour le calcul, si nécessaire.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Plafond maximum de l'exonération (ex. 75000).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage utilisé pour calculer l'exonération (ex. 20 pour 20%).", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Seuil utilisé dans le calcul de l'exonération, le cas échéant.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='is_calculated',
            field=models.BooleanField(default=False, help_text="Si vrai, la valeur finale sera calculée à partir d'autres données (ex. : salaire, indice, etc.) plutôt que d'utiliser la valeur par défaut."),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='is_exonerable',
            field=models.BooleanField(default=False, help_text="Indique si ce composant est soumis à un calcul d'exonération."),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
