# Generated by Django 5.0.3 on 2025-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0004_remove_composantsalaire_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composantsalaire',
            name='calc_ceiling',
        ),
        migrations.RemoveField(
            model_name='composantsalaire',
            name='calc_threshold',
        ),
        migrations.RemoveField(
            model_name='composantsalaire',
            name='exo_threshold',
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_base_reference',
            field=models.CharField(default='J11', help_text='Référence au montant de base utilisé dans le calcul.', max_length=50),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_condition_exclusion',
            field=models.JSONField(blank=True, default=list, help_text="Liste de statuts exclus pour le calcul (ex : ['Vacataire', 'Boursier', 'Plateforme'])."),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='calc_rounding',
            field=models.BooleanField(default=True, help_text='Indique si le résultat du calcul doit être arrondi.'),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_base_reference',
            field=models.CharField(default='AI15', help_text="Référence du revenu de base sur lequel l'exonération est calculée.", max_length=50),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_condition_exclusion',
            field=models.JSONField(blank=True, default=list, help_text="Liste des statuts exclus de l’exonération (ex: ['Vacataire', 'Boursier', 'Plateforme'])."),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_indemnite_reference',
            field=models.CharField(default='P15', help_text="Référence de l'indemnité brute avant l'exonération.", max_length=50),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='exo_rounding',
            field=models.BooleanField(default=True, help_text="Indique si le résultat de l'exonération doit être arrondi."),
        ),
        migrations.AddField(
            model_name='composantsalaire',
            name='formula',
            field=models.TextField(blank=True, help_text='Formule facultative décrivant le calcul dans un format libre.', null=True),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='calc_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage appliqué dans le calcul (ex. 10 pour 10%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='category',
            field=models.CharField(choices=[('BASE', 'Salaire de base'), ('PRIME', 'Prime / Sursalaire / Ancienneté'), ('HS', 'Heures supplémentaires'), ('ALLOWANCE', 'Indemnité / Allocation'), ('DEDUCTION', 'Retenue / Cotisation'), ('AUTRE', 'Autre')], default='ALLOWANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Valeur par défaut utilisée si le calcul n'est pas activé.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='exo_ceiling',
            field=models.DecimalField(decimal_places=2, default=75000, help_text="Plafond maximum de l'exonération.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='exo_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text="Pourcentage utilisé pour calculer l'exonération (ex. : 20 pour 20%).", max_digits=5),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='is_calculated',
            field=models.BooleanField(default=True, help_text='Si vrai, la valeur finale sera calculée automatiquement à partir des paramètres ci-dessous.'),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='is_exonerable',
            field=models.BooleanField(default=False, help_text='Indique si ce composant est soumis à une exonération.'),
        ),
        migrations.AlterField(
            model_name='composantsalaire',
            name='nom',
            field=models.CharField(help_text="Libellé du composant, ex : 'Indemnité Résidence'", max_length=100),
        ),
    ]
