# Generated by Django 5.0.3 on 2025-05-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0005_remove_composantsalaire_calc_ceiling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfichedepaie',
            name='composant',
        ),
        migrations.RemoveField(
            model_name='detailfichedepaie',
            name='fiche_de_paie',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='montant',
            new_name='cotisation_assurance',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='fiche_de_paie',
            new_name='fiche',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='cotisation_carfo',
            new_name='abattement_charges_pro',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='cotisation_cnss',
            new_name='masse_salariale_mensuelle',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='salaire_de_base',
            new_name='net_a_payer',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='salaire_net',
            new_name='remuneration_nette',
        ),
        migrations.RenameField(
            model_name='remboursement',
            old_name='montant',
            new_name='avances_sur_solde',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='type_cotisation',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='periode',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='cotisation_caisse_sociale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_base_fiscale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_brut_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_brut_imposable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_net_imposable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='total_exoneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='total_retenues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='vacation_net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='fiche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='salaire.fichedepaie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remboursement',
            name='remboursement_caisse_sociale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ComposantBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_indiciaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_de_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_components', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Exoneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exo_ind_logement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_astreinte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_technicite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_responsabilite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_specifique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_reseau', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_risque', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_garde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_autres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exo_ind_residence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exonerations', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='HeureSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heures', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_supplementaires', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Indemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indemnite_residence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_logement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_astreinte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_technicite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_responsabilite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_specifique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_reseau', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_risque', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_garde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnite_autres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indemnites', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sursalaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='SecuriteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnss_patronale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cnss_employe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carfo_patronale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carfo_employe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securite_social', to='salaire.fichedepaie')),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iuts_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iuts_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fsp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retenue_vacation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='salaire.fichedepaie')),
            ],
        ),
        migrations.DeleteModel(
            name='ComposantSalaire',
        ),
        migrations.DeleteModel(
            name='DetailFicheDePaie',
        ),
    ]
