# Generated by Django 5.0.3 on 2025-05-28 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0006_remove_detailfichedepaie_composant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='fiche_de_paie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salaire.fichedepaie'),
        ),
    ]
