# Generated by Django 5.0.3 on 2025-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0007_paiement_fiche_de_paie'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
