# Generated by Django 5.0.3 on 2025-06-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0008_parametre_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='footer',
            field=models.TextField(default='Centre MURAZ, 2054, Avenue Mamadou KONATE, Lot 218, Bobo-Dioulasso - Burkina Faso'),
        ),
    ]
